services:
  banking:
    build: 
      context: ..
      dockerfile: container/Dockerfile

    container_name: banking-app
    
    env_file:
      - ../.env

    ports:
      - "3000:3000"

    environment:
      DB_PATH: /app/data/banking.db
      NODE_ENV: production
      PORT: 3000

    volumes:
      - ../data:/app/data

    restart: unless-stopped